---
# For complete sample of all build and test jobs,
# see <gecko>/testing/taskcluster/tasks/branches/base_job_flags.yml

$inherits:
  from: tasks/branches/base_job_flags.yml

builds:
  linux64-mulet:
    platforms:
      - Mulet Linux
    types:
      opt:
        task: tasks/builds/mulet_linux.yml
  emulator-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_kk_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_kk_debug.yml
  emulator-x86-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_x86_kk_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_x86_kk_debug.yml
  emulator-l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_l_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_l_debug.yml
  emulator-jb:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_jb_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_jb_debug.yml
  emulator:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_emulator_ics_opt.yml
      debug:
        task: tasks/builds/b2g_emulator_ics_debug.yml
  aries:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_opt.yml
      debug:
        task: tasks/builds/b2g_aries_spark_debug.yml
  aries-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_aries_spark_eng.yml
  flame-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_opt.yml
      debug:
        task: tasks/builds/b2g_flame_kk_debug.yml
  flame-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_eng.yml
  flame-kk-spark-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_flame_kk_spark_eng.yml
  nexus-4:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_4_user.yml
  nexus-4-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_4_eng.yml
  nexus-4-kk:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_4_kk_user.yml
  nexus-4-kk-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_4_kk_eng.yml
  nexus-5l:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_5l_user.yml
  nexus-5l-eng:
    platforms:
      - b2g
    types:
      opt:
        task: tasks/builds/b2g_nexus_5l_eng.yml

tests:
  cppunit:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_cpp_unit.yml
      tasks/builds/b2g_emulator_ics_debug.yml:
        task: tasks/tests/b2g_emulator_cpp_unit.yml
  crashtest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_crashtest.yml
  gaia-unit-oop:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_gaia_unit_oop.yml
  marionette:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_marionette.yml
  marionette-webapi:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_marionette_webapi.yml
  mochitest:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/b2g_emulator_ics_debug.yml:
        task: tasks/tests/b2g_emulator_mochitest.yml
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_mochitests.yml
  reftest:
    allowed_build_tasks:
      tasks/builds/mulet_linux.yml:
        task: tasks/tests/mulet_reftests.yml
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_reftest.yml
  xpcshell:
    allowed_build_tasks:
      tasks/builds/b2g_emulator_ics_opt.yml:
        task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
      tasks/builds/b2g_emulator_ics_debug.yml:
        task: tasks/tests/b2g_emulator_xpcshell_chunked.yml
